-- SpacedRepetitionApp — Supabase schema
-- Run this in the SQL editor of a fresh Supabase project to recreate the
-- tables the app expects (core/database.py talks to these via PostgREST).
--
-- Tables created here have Row Level Security OFF by default (Supabase's
-- SQL editor does not enable it automatically). The app authenticates with
-- a bare API key (SUPABASE_URL / SUPABASE_KEY) and no Supabase Auth
-- session, so leave RLS disabled unless you add policies that permit the
-- anon/service key you configure in .env.

create table if not exists mcqs (
    id              bigint generated by default as identity primary key,
    question        text not null,
    option_a        text not null,
    option_b        text not null,
    option_c        text not null,
    option_d        text not null,
    correct_answer  text not null check (correct_answer in ('A','B','C','D')),
    subject         text default '',
    topic           text default '',
    subtopic        text not null default '',
    explanation     text default '',
    question_type   text not null default 'STATIC'
                        check (question_type in ('STATIC','CURRENT_AFFAIRS','BIHAR_GK')),
    event_date      date,
    -- Short human-typeable code (e.g. "Q7K2N9XF"), assigned by the app on
    -- creation and used to look a question up directly — see core/database.py
    -- (_generate_public_id / get_mcq_by_public_id). Nullable so pre-existing
    -- rows can be backfilled by the app's sync instead of failing this DDL.
    public_id       text unique,
    created_at      timestamptz not null default now()
);

create index if not exists idx_mcqs_subject on mcqs(subject);
create index if not exists idx_mcqs_topic on mcqs(topic);
create index if not exists idx_mcqs_subject_topic on mcqs(subject, topic);

-- Run this instead if the table already exists without the column:
-- alter table mcqs add column if not exists public_id text unique;

-- next_review_date is intentionally `date`, not `timestamp` — matches the
-- original project's column type, which core/database.py already has
-- explicit handling for (see _snap_midnight / soft_sync in database.py).
create table if not exists card_progress (
    id                  bigint generated by default as identity primary key,
    mcq_id              bigint unique not null references mcqs(id) on delete cascade,
    ease_factor         real not null default 2.5,
    interval_days       integer not null default 0,
    repetitions         integer not null default 0,
    next_review_date    date not null default current_date,
    last_reviewed_at    timestamptz,
    again_count         integer not null default 0,
    review_tag          text not null default ''
);

create index if not exists idx_cp_next_review on card_progress(next_review_date);

create table if not exists review_logs (
    id            bigint generated by default as identity primary key,
    mcq_id        bigint not null references mcqs(id) on delete cascade,
    quality       integer not null,
    was_correct   boolean not null,
    reviewed_at   timestamptz not null default now()
);

create index if not exists idx_rl_reviewed_at on review_logs(reviewed_at);

create table if not exists hidden_subjects (
    subject text primary key
);

create table if not exists hidden_topics (
    subject text not null,
    topic   text not null,
    primary key (subject, topic)
);
